forci_http_logger_bundle_message_view:
    path:      /{id}/view/{class}
    controller: Forci\Bundle\HttpLogger\Controller\MessageController:viewAction

forci_http_logger_bundle_message_view_raw:
    path:      /{id}/view-raw/{class}
    controller: Forci\Bundle\HttpLogger\Controller\MessageController:viewRawAction